version: '3.8'
services:
  contour:
    image: 'keenanrnicholson/server-tools:local'
    container_name: server-tools
    restart: unless-stopped
    volumes:
      - ../library/db:/db
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'America/New_York'