version: '3'
services:
  dev:
    image: server-tools:dev
    container_name: server-tools-dev
    volumes:
      - ../node_modules:/app/node_modules
      - ../:/app

    environment:
      TZ: 'America/New_York'

    stop_signal: SIGKILL
    working_dir: /app
    command: sh -c "pnpm i && pnpm run dev"
    init: true
    tty: true
    stdin_open: true