version: '3.8'
services:
  contour:
    image: 'server-tools:local'
    container_name: server-tools
    restart: unless-stopped
    
    environment:
      PUID: 1000
      PGID: 1000
      NAME: tesler
      MQTT_VERSION: '4'
      MQTT_HOSTNAME: ${MQTT_HOSTNAME}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      SSH_USERNAME: ${SSH_USERNAME}
      SSH_PASSWORD: ${SSH_PASSWORD}