version: '3.8'
services:
  contour:
    image: 'keenanrnicholson/server-tools:main'
    container_name: server-tools
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'America/New_York'